# Example CEL policy rules
rules:
- name: deny-github-delete-file
  description: Deny github delete file
  enabled: true
  expression: |-
    get(request, "method", "") == "tools/call" &&
    get(request.params, "name", "") == "github__delete_file"
  action: deny
  message: Denied access to github__delete_file
- name: deny-github-delete-workflow-run-logs
  description: Deny github__delete_workflow_run_logs
  enabled: true
  expression: |-
    get(request, "method", "") == "tools/call" &&
    get(request.params, "name", "") == "github__delete_workflow_run_logs"
  action: deny
  message: Denied access to github__delete_workflow_run_logs
