// Package cliproxy provides an HTTP client for communicating with the Maybe Don't
// gateway's CLI validation API. It sends command validation requests and receives
// policy decisions about whether commands should be allowed to execute.
package cliproxy

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"
)

const (
	// DefaultTimeout is used when no timeout is specified in ClientConfig.
	DefaultTimeout = 30 * time.Second

	// validateEndpoint is the gateway API endpoint for CLI command validation.
	validateEndpoint = "/api/v1/cli/validate"
)

// ValidationRequest represents a request to validate a CLI command before execution.
// This matches the gateway's CLIValidationRequest format.
type ValidationRequest struct {
	// Command is the CLI executable name (e.g., "gh", "aws", "kubectl").
	Command string `json:"command"`

	// Arguments contains the command arguments. Can be an empty array.
	Arguments []string `json:"arguments"`

	// WorkingDirectory is the current working directory where the command will execute.
	WorkingDirectory string `json:"working_directory,omitempty"`

	// ClientInfo contains optional client environment information for audit attribution.
	ClientInfo *ClientInfo `json:"client_info,omitempty"`
}

// ClientInfo contains client environment information collected by the CLI wrapper.
// All fields are optional and used for audit logging and policy evaluation.
type ClientInfo struct {
	// Hostname is the client machine hostname (from os.Hostname()).
	Hostname string `json:"hostname,omitempty"`

	// Username is the current user (from os/user.Current()).
	Username string `json:"username,omitempty"`

	// OS is the operating system (from runtime.GOOS: "darwin", "linux", "windows").
	OS string `json:"os,omitempty"`

	// OSVersion is the OS version string (best-effort, platform-specific).
	OSVersion string `json:"os_version,omitempty"`

	// Arch is the CPU architecture (from runtime.GOARCH: "amd64", "arm64", etc.).
	Arch string `json:"arch,omitempty"`

	// Shell is the user's shell (from $SHELL on Unix, $COMSPEC on Windows).
	Shell string `json:"shell,omitempty"`

	// CLIVersion is the version of the maybe-dont CLI wrapper.
	CLIVersion string `json:"cli_version,omitempty"`
}

// ValidationResponse contains the gateway's decision about a command validation request.
// This matches the gateway's CLIValidationResponse format.
type ValidationResponse struct {
	// RequestID is the request identifier, either from the X-Request-ID header
	// or generated by the server (32-character hex string).
	RequestID string `json:"request_id"`

	// Allowed indicates whether the command is permitted to execute.
	Allowed bool `json:"allowed"`

	// ValidationRequired indicates whether the command required policy validation.
	// When false, the command was not in the validate_commands list and was allowed
	// without policy evaluation.
	ValidationRequired bool `json:"validation_required"`

	// Message is a human-readable description of the validation result.
	Message string `json:"message"`

	// ActionReason explains why the action was taken. Only populated when Allowed is false.
	// Values: "request_policy" (policy denied the command).
	ActionReason string `json:"action_reason,omitempty"`

	// ServerVersion is the gateway version (from build info).
	ServerVersion string `json:"server_version"`

	// ClientVersion is echoed from the request's client_info.cli_version if provided.
	ClientVersion string `json:"client_version,omitempty"`

	// Results contains per-policy evaluation results.
	// Empty when ValidationRequired is false.
	Results []PolicyResult `json:"results"`
}

// PolicyResult represents a single policy evaluation result.
type PolicyResult struct {
	// PolicyName is the name of the policy from the rule definition.
	PolicyName string `json:"policy_name"`

	// PolicyType indicates the type of policy: "cel" or "ai".
	PolicyType string `json:"policy_type"`

	// Action is the result of the policy evaluation: "allow", "deny", or "redact".
	Action string `json:"action"`

	// Message is an optional explanation from the policy evaluation.
	Message string `json:"message,omitempty"`
}

// ErrorResponse represents an error returned by the gateway API.
type ErrorResponse struct {
	// Error is the error type/code.
	Error string `json:"error"`

	// Message provides details about the error.
	Message string `json:"message"`
}

// ClientConfig holds configuration for the cliproxy Client.
type ClientConfig struct {
	// ServerURL is the base URL of the Maybe Don't gateway (e.g., "http://localhost:8080").
	ServerURL string

	// Timeout is the HTTP request timeout. Defaults to 30 seconds if not specified.
	Timeout time.Duration

	// ClientID is an optional identifier sent in the X-Maybe-Dont-Client-ID header.
	ClientID string
}

// Client communicates with the Maybe Don't gateway for CLI command validation.
type Client struct {
	serverURL  string
	clientID   string
	httpClient *http.Client
}

// NewClient creates a new cliproxy Client with the given configuration.
func NewClient(cfg ClientConfig) *Client {
	timeout := cfg.Timeout
	if timeout == 0 {
		timeout = DefaultTimeout
	}

	return &Client{
		serverURL: cfg.ServerURL,
		clientID:  cfg.ClientID,
		httpClient: &http.Client{
			Timeout: timeout,
		},
	}
}

// Validate sends a command validation request to the gateway and returns the decision.
// It returns an error if the request fails or the gateway returns an error response (400+).
func (c *Client) Validate(ctx context.Context, req ValidationRequest) (*ValidationResponse, error) {
	// Serialize request body
	body, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal request: %w", err)
	}

	// Build HTTP request
	url := c.serverURL + validateEndpoint
	httpReq, err := http.NewRequestWithContext(ctx, http.MethodPost, url, bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	httpReq.Header.Set("Content-Type", "application/json")
	if c.clientID != "" {
		httpReq.Header.Set("X-Maybe-Dont-Client-ID", c.clientID)
	}

	// Send request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		// Check for context cancellation/deadline
		if ctx.Err() != nil {
			return nil, ctx.Err()
		}
		return nil, fmt.Errorf("request failed: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()

	// Handle error responses (400+)
	if resp.StatusCode >= 400 {
		var errResp ErrorResponse
		if err := json.NewDecoder(resp.Body).Decode(&errResp); err != nil {
			return nil, fmt.Errorf("server returned status %d", resp.StatusCode)
		}
		return nil, fmt.Errorf("%s: %s", errResp.Error, errResp.Message)
	}

	// Parse successful response
	var validationResp ValidationResponse
	if err := json.NewDecoder(resp.Body).Decode(&validationResp); err != nil {
		return nil, fmt.Errorf("failed to decode response: %w", err)
	}

	return &validationResp, nil
}
