package gateway

import (
	"context"
	"encoding/json"
	"maps"
	"net/http"
	"strings"
	"time"

	"github.com/mark3labs/mcp-go/mcp"
	"github.com/maybedont/maybe-dont/internal/config"
	"go.uber.org/zap"
)

// RiskLevel represents the security risk level of an action.
// These map directly to OpenHands' SecurityRisk enum values.
type RiskLevel string

const (
	RiskLevelHigh    RiskLevel = "high"
	RiskLevelMedium  RiskLevel = "medium"
	RiskLevelLow     RiskLevel = "low"
	RiskLevelUnknown RiskLevel = "unknown"
)

// ActionValidationRequest represents an action validation request from an external agent framework.
// This is the JSON request body for POST /api/v1/action/validate.
type ActionValidationRequest struct {
	// ActionType identifies the action category (e.g., "tool_call").
	// This field is optional for v1 (always evaluated as a tool call).
	ActionType string `json:"action_type,omitempty"`

	// Target is the name of the tool or action being called (e.g., "execute_bash").
	// This field is required.
	Target string `json:"target"`

	// Parameters contains the structured arguments for the action.
	// This field is optional.
	Parameters map[string]any `json:"parameters,omitempty"`

	// Actor identifies who is performing the action (e.g., "openhands-agent").
	// Used as a fallback for client_id when X-Maybe-Dont-Client-ID header is not set.
	Actor string `json:"actor,omitempty"`

	// ExternalID is a caller-provided correlation ID (e.g., OpenHands action.id).
	// Included in the audit log for correlating gateway entries back to the caller's records.
	ExternalID string `json:"external_id,omitempty"`

	// Context provides additional context about the action for AI policy evaluation.
	Context *ActionContext `json:"context,omitempty"`
}

// ActionContext provides additional context about an action for richer AI policy evaluation.
type ActionContext struct {
	// Thought is the agent's reasoning for performing this action.
	// Included in AI policy evaluation prompts to improve accuracy.
	Thought string `json:"thought,omitempty"`

	// Summary is a concise description of the action.
	Summary string `json:"summary,omitempty"`
}

// ActionValidationResponse represents the validation result returned by the gateway.
// This is the JSON response body for POST /api/v1/action/validate.
type ActionValidationResponse struct {
	// RequestID is the request identifier, either from the X-Request-ID header
	// or generated by the server (32-character hex string).
	RequestID string `json:"request_id"`

	// Allowed indicates whether the action is permitted to execute.
	Allowed bool `json:"allowed"`

	// RiskLevel indicates the security risk level: "high", "medium", "low", or "unknown".
	// Maps directly to OpenHands' SecurityRisk enum.
	RiskLevel RiskLevel `json:"risk_level"`

	// Message is a human-readable description of the validation result.
	Message string `json:"message"`

	// ServerVersion is the gateway version (from build info).
	ServerVersion string `json:"server_version"`

	// Results contains per-policy evaluation results.
	// Empty when no policies are configured.
	Results []CLIPolicyResult `json:"results"`
}

// ActionValidationError represents an error response from the action validation endpoint.
type ActionValidationError struct {
	// Error is the error code. Values:
	// - "invalid_request": Malformed request body
	// - "missing_target": Required target field is empty
	// - "invalid_content_type": Content-Type header is not application/json
	Error string `json:"error"`

	// Message is a human-readable description of the error.
	Message string `json:"message"`
}

// ActionValidationHandlerConfig configures the action validation HTTP handler.
type ActionValidationHandlerConfig struct {
	// Logger is the session logger for request logging.
	Logger *config.SessionLogger

	// Version is the gateway version string returned in responses.
	Version string

	// AuditWriter is used to write audit log entries for action validations.
	// If nil, no audit logging is performed.
	AuditWriter AuditWriter

	// OnValidation is an optional callback invoked during validation processing.
	// This is primarily used for testing to capture the validation context.
	OnValidation func(*CLIValidationContext)

	// CELEngine is the CEL policy engine for deterministic rule evaluation.
	// If nil, CEL validation is skipped.
	CELEngine *CELPolicyEngine

	// AIEngine is the AI policy engine for context-aware validation.
	// If nil, AI validation is skipped.
	AIEngine *AIPolicyEngine

	// MaxBlockingMs is the maximum cumulative time to block a request
	// waiting for all validation decisions (default: 90000ms).
	MaxBlockingMs int

	// MaxRuleEvaluationMs is the maximum time for any single rule evaluation
	// (default: 45000ms).
	MaxRuleEvaluationMs int
}

// ActionValidationHandler handles /api/v1/action/validate requests.
type ActionValidationHandler struct {
	config ActionValidationHandlerConfig
}

// NewActionValidationHandler creates a new action validation handler.
func NewActionValidationHandler(cfg ActionValidationHandlerConfig) *ActionValidationHandler {
	return &ActionValidationHandler{config: cfg}
}

// ServeHTTP handles action validation requests.
func (h *ActionValidationHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	// Record validation start time for audit logging
	validationStart := time.Now().UTC()

	w.Header().Set("Content-Type", "application/json")

	// Validate Content-Type (accept with charset parameters like "application/json; charset=utf-8")
	if !strings.HasPrefix(r.Header.Get("Content-Type"), "application/json") {
		h.writeError(w, http.StatusBadRequest, "invalid_content_type",
			"Content-Type must be application/json")
		return
	}

	// Parse request body
	var req ActionValidationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		h.writeError(w, http.StatusBadRequest, "invalid_request",
			"Failed to parse request body: "+err.Error())
		return
	}

	// Validate required fields
	if req.Target == "" {
		h.writeError(w, http.StatusBadRequest, "missing_target",
			"Required field 'target' is empty")
		return
	}

	// Extract request context from headers
	ctx := h.extractContext(r)

	// Use actor from request body as client ID if header wasn't provided
	if ctx.ClientID == "" && req.Actor != "" {
		ctx.ClientID = req.Actor
	}

	// Call OnValidation callback if set (for testing)
	if h.config.OnValidation != nil {
		h.config.OnValidation(ctx)
	}

	// Attach request ID to context so downstream loggers include it
	reqCtx := context.WithValue(r.Context(), config.RequestIDKey, ctx.RequestID)

	// Evaluate policies
	validationResults := h.evaluatePolicies(reqCtx, &req)

	// Derive risk level from validation results
	riskLevel := h.deriveRiskLevel(validationResults)

	// Build response
	resp := ActionValidationResponse{
		RequestID:     ctx.RequestID,
		Allowed:       validationResults.Allowed,
		RiskLevel:     riskLevel,
		Message:       validationResults.Message,
		ServerVersion: h.config.Version,
		Results:       h.convertToResults(validationResults),
	}
	_ = json.NewEncoder(w).Encode(resp)

	// Determine audit action based on validation result
	auditAction := "allow"
	if !validationResults.Allowed {
		auditAction = "deny"
	}
	h.writeAuditEntryWithValidation(validationStart, r, &req, ctx, auditAction, validationResults)
}

// toCallToolRequest converts an ActionValidationRequest to an mcp.CallToolRequest
// for evaluation by the CEL and AI policy engines.
func (h *ActionValidationHandler) toCallToolRequest(req *ActionValidationRequest) mcp.CallToolRequest {
	// Build arguments map, enriching with context if provided.
	// Context fields are included in the arguments so they appear in the operation JSON
	// that AI policy engines evaluate. This enriches AI rule evaluation with agent reasoning.
	args := req.Parameters
	if req.Context != nil && (req.Context.Thought != "" || req.Context.Summary != "") {
		// Copy parameters to avoid mutating the original request
		args = make(map[string]any, len(req.Parameters)+1)
		maps.Copy(args, req.Parameters)
		agentContext := make(map[string]any)
		if req.Context.Thought != "" {
			agentContext["thought"] = req.Context.Thought
		}
		if req.Context.Summary != "" {
			agentContext["summary"] = req.Context.Summary
		}
		args["_agent_context"] = agentContext
	}

	return mcp.CallToolRequest{
		Request: mcp.Request{Method: "tools/call"},
		Params: mcp.CallToolParams{
			Name:      req.Target,
			Arguments: args,
		},
	}
}

// evaluatePolicies runs the action through CEL and AI policy engines.
// Returns combined validation results from all configured engines.
func (h *ActionValidationHandler) evaluatePolicies(ctx context.Context, req *ActionValidationRequest) ValidationResults {
	// If no engines configured, allow by default
	if h.config.CELEngine == nil && h.config.AIEngine == nil {
		return ValidationResults{
			Results: []ValidationResult{},
			Allowed: true,
			Message: "No validation policies configured",
		}
	}

	// Convert to mcp.CallToolRequest for engine evaluation
	mcpReq := h.toCallToolRequest(req)

	// Create blocking budget for validation timing
	maxBlockingMs := h.config.MaxBlockingMs
	if maxBlockingMs == 0 {
		maxBlockingMs = 90000 // Default 90s
	}
	budget := NewBlockingBudget(int64(maxBlockingMs))

	var finalResults ValidationResults
	finalResults.Allowed = true // Start with allow, any deny will flip this

	// Evaluate CEL policies if engine is configured
	if h.config.CELEngine != nil {
		celResults, err := h.config.CELEngine.EvaluateToolCall(ctx, mcpReq, budget)
		if err != nil {
			h.config.Logger.Error(ctx, "CEL action validation failed",
				zap.Error(err),
				zap.String("target", req.Target),
			)
			// Continue with fail-open behavior
			finalResults.FailedOpen = true
		} else {
			finalResults.Results = append(finalResults.Results, celResults.Results...)
			finalResults.AllowCount += celResults.AllowCount
			finalResults.DenyCount += celResults.DenyCount
			if celResults.RulesDetails != nil {
				finalResults.RulesDetails = celResults.RulesDetails
			}
			if celResults.AuditModeBypass {
				finalResults.AuditModeBypass = true
			}
			// If CEL denies and it's not audit-only, update final result
			if !celResults.Allowed && !celResults.AuditModeBypass {
				finalResults.Allowed = false
				if finalResults.Message == "" {
					finalResults.Message = celResults.Message
				}
			}
		}
	}

	// Evaluate AI policies if engine is configured
	if h.config.AIEngine != nil {
		aiResults, err := h.config.AIEngine.EvaluateToolCall(ctx, mcpReq, budget)
		if err != nil {
			h.config.Logger.Error(ctx, "AI action validation failed",
				zap.Error(err),
				zap.String("target", req.Target),
			)
			// Continue with fail-open behavior
			finalResults.FailedOpen = true
		} else {
			finalResults.Results = append(finalResults.Results, aiResults.Results...)
			finalResults.AllowCount += aiResults.AllowCount
			finalResults.DenyCount += aiResults.DenyCount
			if aiResults.AIDetails != nil {
				finalResults.AIDetails = aiResults.AIDetails
			}
			// Capture async completion channel for audit logging
			if aiResults.AsyncCompletion != nil {
				finalResults.AsyncCompletion = aiResults.AsyncCompletion
			}
			if aiResults.AuditModeBypass {
				finalResults.AuditModeBypass = true
			}
			// If AI denies and it's not audit-only, update final result
			if !aiResults.Allowed && !aiResults.AuditModeBypass {
				finalResults.Allowed = false
				if finalResults.Message == "" {
					finalResults.Message = aiResults.Message
				}
			}
		}
	}

	// AuditModeBypass only applies when the final action is allow (the deny was bypassed).
	// If an enforced deny from any engine overrides it, clear the bypass flag —
	// the request was denied, no bypass occurred.
	if !finalResults.Allowed {
		finalResults.AuditModeBypass = false
	}

	// Set default message if none set
	if finalResults.Message == "" {
		if finalResults.Allowed {
			finalResults.Message = "Action approved by policy"
		} else {
			finalResults.Message = "Action denied by policy"
		}
	}

	return finalResults
}

// deriveRiskLevel maps ValidationResults to a risk level string.
//
//	allowed=false                               → "high"
//	allowed=true, AuditModeBypass               → "medium"
//	allowed=true, at least one engine evaluated  → "low"
//	no engines evaluated (no config, errors)     → "unknown"
func (h *ActionValidationHandler) deriveRiskLevel(results ValidationResults) RiskLevel {
	if !results.Allowed {
		return RiskLevelHigh
	}
	if results.AuditModeBypass {
		return RiskLevelMedium
	}
	// Check if any engine produced evaluation results.
	// The CEL engine populates Results and RulesDetails; the AI engine populates AIDetails
	// (synchronous path) or sets AllowCount (async audit_only path where AIDetails is deferred).
	if len(results.Results) > 0 || results.RulesDetails != nil || results.AIDetails != nil || results.AllowCount > 0 {
		return RiskLevelLow
	}
	return RiskLevelUnknown
}

// convertToResults converts ValidationResults to CLIPolicyResult slice for the response.
func (h *ActionValidationHandler) convertToResults(results ValidationResults) []CLIPolicyResult {
	policyResults := make([]CLIPolicyResult, 0, len(results.Results))
	for _, r := range results.Results {
		policyResults = append(policyResults, CLIPolicyResult{
			PolicyName: r.PolicyName,
			PolicyType: r.PolicyType,
			Action:     string(r.Action),
			Message:    r.Message,
		})
	}
	return policyResults
}

// extractContext extracts request ID and client ID from HTTP headers.
// If X-Request-ID is not provided, a 32-character hex string is generated.
func (h *ActionValidationHandler) extractContext(r *http.Request) *CLIValidationContext {
	ctx := &CLIValidationContext{
		RequestID: r.Header.Get("X-Request-ID"),
		ClientID:  r.Header.Get("X-Maybe-Dont-Client-ID"),
	}

	// Generate request ID if not provided
	if ctx.RequestID == "" {
		id, err := GenerateRequestID()
		if err != nil {
			h.config.Logger.Logger().Warn("failed to generate request ID, using fallback",
				zap.Error(err))
			ctx.RequestID = "00000000000000000000000000000000"
		} else {
			ctx.RequestID = id
		}
	}

	return ctx
}

// writeError writes a JSON error response.
func (h *ActionValidationHandler) writeError(w http.ResponseWriter, status int, code, message string) {
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(ActionValidationError{
		Error:   code,
		Message: message,
	})
}

// writeAuditEntryWithValidation creates and writes an audit entry including validation results.
func (h *ActionValidationHandler) writeAuditEntryWithValidation(
	validationStart time.Time,
	r *http.Request,
	req *ActionValidationRequest,
	ctx *CLIValidationContext,
	action string,
	results ValidationResults,
) {
	if h.config.AuditWriter == nil {
		return
	}

	now := time.Now().UTC()

	// Build validation info from results
	var requestValidation *AuditValidationInfo
	if results.RulesDetails != nil || results.AIDetails != nil {
		requestValidation = &AuditValidationInfo{
			CEL: results.RulesDetails,
			AI:  results.AIDetails,
		}
	}

	// Determine action reason
	// AuditModeBypass only applies when the final action is allow (the deny was bypassed).
	// When the final action is deny (from an enforced rule), AuditModeBypass may still be set
	// from a different engine's audit_only deny, but the reason should reflect the enforced deny.
	actionReason := ""
	if !results.Allowed {
		// Final action is deny — the reason is the policy, not audit_mode
	} else if results.AuditModeBypass {
		actionReason = string(ActionReasonAuditMode)
	} else if results.FailedOpen {
		actionReason = string(ActionReasonFailOpen)
	}

	// Build action info for the audit entry
	// Reuse the Tool field with a synthetic tool name from the action target
	entry := &AuditEntry{
		Source:            "action",
		ValidationStarted: validationStart.Format(time.RFC3339Nano),
		CreatedAt:         now.Format(time.RFC3339Nano),
		Tool: &AuditToolInfo{
			Name:         req.Target,
			PrefixedName: req.Target,
			Params:       req.Parameters,
		},
		UpstreamRequest: UpstreamRequestInfo{
			RequestID:  ctx.RequestID,
			ExternalID: req.ExternalID,
			ClientID:   ctx.ClientID,
			ClientIP:   r.RemoteAddr,
			UserAgent:  r.Header.Get("User-Agent"),
		},
		RequestValidation: requestValidation,
		Action:            action,
		ActionReason:      actionReason,
		DurationMs:        now.Sub(validationStart).Milliseconds(),
	}

	// Write the audit entry (ignore errors - audit logging should not affect response)
	_, _ = h.config.AuditWriter.Write(entry)

	// Handle async AI completion for audit logging
	if results.AsyncCompletion != nil {
		go func() {
			select {
			case completion := <-results.AsyncCompletion:
				if completion.AIDetails != nil && h.config.AuditWriter != nil {
					asyncEntry := &AuditEntry{
						Source:            "action",
						ValidationStarted: validationStart.Format(time.RFC3339Nano),
						CreatedAt:         time.Now().UTC().Format(time.RFC3339Nano),
						Tool: &AuditToolInfo{
							Name:         req.Target,
							PrefixedName: req.Target,
						},
						UpstreamRequest: UpstreamRequestInfo{
							RequestID:  ctx.RequestID + "-async",
							ExternalID: req.ExternalID,
							ClientID:   ctx.ClientID,
						},
						RequestValidation: &AuditValidationInfo{
							AI: completion.AIDetails,
						},
						Action:       action,
						ActionReason: "async_completion",
						DurationMs:   completion.EvaluationMs,
					}
					_, _ = h.config.AuditWriter.Write(asyncEntry)
				}
			case <-time.After(5 * time.Minute):
				logCtx := context.WithValue(context.Background(), config.RequestIDKey, ctx.RequestID)
				h.config.Logger.Debug(logCtx, "Timeout waiting for async AI completion (action validation)")
			}
		}()
	}
}
