name: goreleaser

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ['v*']

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      flags: ""
    steps:
      - if: ${{ !startsWith(github.ref, 'refs/tags/v') }}
        run: echo "flags=--snapshot" >> $GITHUB_ENV
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.24
          cache: true
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser-pro
          version: latest
          args: release --clean ${{ env.flags }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GORELEASER_KEY: ${{ secrets.GORELEASER_KEY }}
      - name: Update website repository
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          VERSION=${{ github.ref }}
          echo "Running release script for version: $VERSION"

          # Set environment variables for the release script
          export GITHUB_TOKEN="${{ secrets.WEBSITE_DEPLOY_TOKEN }}"
          export VERSION="$VERSION"
          export DIST_DIR="./dist"

          # Run the release script
          ./scripts/release.sh --merge
